services:
  jenkins:
    build: .
    container_name: jenkins-lts-python
    ports:
      - '8080:8080' # Jenkins UI
      - '50000:50000' # JNLP agent (필요시)
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
